# Generated by Django 4.1.4 on 2022-12-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_address_ad_addres_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
