# Generated by Django 4.1.4 on 2022-12-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_addres_ad_address_rename_title_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
